import { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useWindowDimensions from './hooks/useWindowDimensions';

const Nav = () => {
  console.log('yo');
}
Nav();

export default function Home() {
  const [lock, setLock] = useState(false);
  const {height, width} = useWindowDimensions();
  return (
    <>
      <Head>
        <title>BeatHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.jumbotron}>
        <Image className={styles.jumboImg} src='/bg.jpg' layout='fill' />
        <h1 className={styles.mainTitle}>JMCC <br /><i>Beats</i></h1>
        <nav className={styles.nav}>
          <ul>
            <li>Subscribe</li>
            <li>Merch</li>
            <li>Cart</li>
          </ul>
        </nav>
      </header>
      <main className={styles.main + ' p-5'}>
        {/* - if the width of the screen is less than or equal to 375px, then change the height of the player to be 80px instead of 380px
            - if the screen is wider than 700px, set the width of the player to 700px */}
        <section className={styles.music}>
          <iframe style={{ borderRadius: 12 + 'px'}} src="https://open.spotify.com/embed/album/7HpeKG3lY2QcDAJ9FOYIvF?utm_source=generator" width="700" height="380" frameBorder="0" allowFullScreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
        </section>
        <section>
          <h1>Blog Post</h1>
          {/* width: {width} ~ height: {height} */}
        </section>
        <section>
          <h1>Merchandise</h1>
          <ul>
            <li>item</li>
            <li>item</li>
            <li>item</li>
          </ul>
        </section>
      </main>

      <footer style={{ position: 'relative', }} className={styles.footer}>
        <Image src='/icon.png' width='100' height='100' />JMCC BEATS
      </footer>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossOrigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossOrigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossOrigin="anonymous"></script>
    </>
  )
}
